// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpSZxjiP5ksuc3H62Klms8uQCoflwLXI',
    appId: '1:919027701670:web:a914f31820318cc89a6167',
    messagingSenderId: '919027701670',
    projectId: 'oma-bayti',
    authDomain: 'oma-bayti.firebaseapp.com',
    storageBucket: 'oma-bayti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfAyDC4dNVutt9KFqRCs45mtFL2SX8tg',
    appId: '1:919027701670:android:82596236960d33cd9a6167',
    messagingSenderId: '919027701670',
    projectId: 'oma-bayti',
    storageBucket: 'oma-bayti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLpEXKAO3ADjHNYol-ABGH04T8UtsaAY',
    appId: '1:919027701670:ios:6eb5d27061416de99a6167',
    messagingSenderId: '919027701670',
    projectId: 'oma-bayti',
    storageBucket: 'oma-bayti.appspot.com',
    iosBundleId: 'com.omaGroup.bayti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLpEXKAO3ADjHNYol-ABGH04T8UtsaAY',
    appId: '1:919027701670:ios:2294b55c76bcb68d9a6167',
    messagingSenderId: '919027701670',
    projectId: 'oma-bayti',
    storageBucket: 'oma-bayti.appspot.com',
    iosBundleId: 'com.omaGroup.bayti.RunnerTests',
  );
}
